### ISSUE TITLE
[Question] Go->PHP and vice versa

### ISSUE THREAD

**Issue by g41797** [cloudevents/sdk-go#1006]
We are going to use CE as base for negotiation between PHP based producers and go based consumers.
I know that there are a lot of CE adapters.But anyway - did you test compatibility between php serialization and go deserialization? (and vice versa)

**Comment by duglin** [comment]
I'm not aware of any explicit testing for that but since the language used to generate or read the CloudEvent isn't exposed as part of the CE, nor should it change how the CE is serialized, there shouldn't be any issue with this working.

**Comment by g41797** [comment]
looks like a [question of faith](https://github.com/cloudevents/sdk-php/issues/55#issuecomment-1900099543)
what was the purpose of sdks development?
just prototype?

**Comment by duglin** [comment]
it's not so much about "faith" as much as the spec just defines what should appear on the wire. None of that is dependent on the language used by either side. Yes there could be bugs, but you could see similar bugs using the same language on both sides.

Now, having said that, sure there could be some testing done (just to be sure) between SDKs and there's this repo: https://github.com/cloudevents/conformance which (I think) tried to include a bit of that testing. It's been a while since people have played with that repo though, but I know it is on some folk's todo list. If you're interested in helping in this space we'd love that
