### ISSUE TITLE
Send signature accepts Event more than *Event

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#190]
Hi,
Since Event contains the buffered body of the event (look https://github.com/cloudevents/sdk-go/issues/186) and inlining is not guaranteed, the `Send` signature (and all methods in that call tree with `Event` parameter like `obsSend`, `transport.Send`, etc) should accept `*Event`, to avoid useless memory copy. If no inlining happens and the event is big, this could cause a big performance issue

**Comment by n3wscott** [comment]
Thanks for the issue. will look into it.

**Comment by alanconway** [comment]
I agree with pass-by-pointer, for a different reason: Context is a pointer, so not copied. Large Data will be []byte or string, also not copied. Passing *Event is good because it clarifies that the event is *not* copied. Passing Event by value might give the mistaken impression that the whole event is copied, when in fact the Context and Data most likely are not.

Of course @slinkydeveloper is right that pass-by-pointer will eliminate some copying (e.g. the {pointer,int,int} struct that is the base of []byte) which is also good. I wouldn't expect big improvements in a memory profile however.

**Comment by n3wscott** [comment]
Let's look at this in v2.

**Comment by slinkydeveloper** [comment]
This is addressed by bindings
