### ISSUE TITLE
Don't buffer and parse the body when an event is received

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#191]
Now when you receive an event the `Data` is fully buffered (and even parsed if it's a json). It could be useful to have a configuration flag for:

- When possible (eg binary mode in http), don't buffer the Data, but just return the `io.Reader` 
- Don't parse the body to json when not required

**Comment by n3wscott** [comment]
I think we want to do this in v2 of the sdk. It will really speed things up.

cc: @alanconway

**Comment by alanconway** [comment]
It won't speed things up unless 

a) events carry very large data AND
b) the event consume is able to process the data in pieces.

I don't think that b) will hold very often for endpoint event aps, but would in intermediaries that forward events. If we do add this feature the pkg/binding.Message needs to offer that so event data can be streamed between transports.

**Comment by slinkydeveloper** [comment]
@alanconway b situation it's definitely the target of eventing components

**Comment by alanconway** [comment]
+1 to using io.Reader in the Go API. Helps big data, doesn't hurt small data, is a well-known pattern from net.http.

@slinkydeveloper could you elaborate on large-data use cases for eventing? I see eventing as a complement to HTTP, and HTTP is already very good at distributing large data  resources.

Real example: Pixar rendering farms handle distribute very large data over very large numbers of compute nodes. They use AMQP "events" to negotiate workloads, advertize available compute capacity and available work that needs rendering. However they switch tacks to actually ship chunks of movies around  (motley assortment of NFS and home-brew AMQP-based stuff) 

Point is: if I was doing that in the cloud, I would use eventing for workload negotiation and such "metadata", possibly with an AMQP or MQTT backbone for that part, but distribute URLs in the events and use HTTP to hit the big resource and compute servers.

**Comment by slinkydeveloper** [comment]
I just found that (probably to avoid data races) there is a copy of the whole event body just before the message is sent https://github.com/cloudevents/sdk-go/blob/a673034672bfdf06d9e270813e982425143260aa/pkg/cloudevents/transport/http/message.go#L123

Can we add a flag or something similar to avoid these behaviours and just share buffers between goroutines? When the message is sent and not used anymore, I assume is safe to share the body buffer with another goroutine without copying it

**Comment by alanconway** [comment]
I'd rather not make this optional - either we ensure it is concurrent-safe to never copy, or it's not safe and we always copy. Otherwise folks will always turn on the "go faster" flag and then be subject to unpredictable races and crashes.

In the current API I think we can document that an Event (and it's Context!) MUST NOT be modified after calling Send() or there will be Undefined Consequences. It is a reasonable constraint and consistent with the general concurrency rules of Go. For example it would also be an error to modify a http.Request in flight.

Ideally the event API would actually have an immutable Event type, that could be something to aim for in v2, although many existing Go APIs don't bother to provide immutable types (e.g. http.Request, http.Header) and assume the user will be smart.

**Comment by slinkydeveloper** [comment]
> I'd rather not make this optional - either we ensure it is concurrent-safe to never copy, or it's not safe and we always copy. Otherwise folks will always turn on the "go faster" flag and then be subject to unpredictable races and crashes.

Makes sense

> In the current API I think we can document that an Event (and it's Context!) MUST NOT be modified after calling Send() or there will be Undefined Consequences. It is a reasonable constraint and consistent with the general concurrency rules of Go. For example it would also be an error to modify a http.Request in flight.

Hmm to me looks like a "shoot in the foot" feature, since there is no type enforcing mechanism to prevent any bad usage. Generally speaking, I think the client APIs should be somewhat safe and prevent bad usages to target creating user applications. The problem is that we (Knative Eventing) need a less safe but faster APIs to build performant cluster services.

**Comment by alanconway** [comment]
> > In the current API I think we can document that an Event (and it's Context!) MUST NOT be modified after calling Send() or there will be Undefined Consequences. It is a reasonable constraint and consistent with the general concurrency rules of Go. For example it would also be an error to modify a http.Request in flight.
> 
> Hmm to me looks like a "shoot in the foot" feature, since there is no type enforcing mechanism to prevent any bad usage. Generally speaking, I think the client APIs should be somewhat safe and prevent bad usages to target creating user applications. The problem is that we (Knative Eventing) need a less safe but faster APIs to build performant cluster services.

Agreed, but I don't think a flag helps because a) "we" are just as likely to screw up as anyone else and b) if there's a "go faster" switch then everyone will turn it on, everyone needs speed. 

I'm not sure this problem applies to the binding model, where Message.Finish() allows Receivers to safely reclaim buffers or other resources in a Message.

**Comment by slinkydeveloper** [comment]
This is addressed by bindings
