### ISSUE TITLE
Implement Partitioning extension

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/sdk-go#200]
Ref: https://github.com/cloudevents/spec/blob/master/extensions/partitioning.md

**Comment by FWiesner** [comment]
I really would love to see this feature implemented. While you want to keep your messaging platform able to scale horizontally, you sometimes cannot accept parallelized and therefore out-of-order delivery of messages. For example when you want to implement a kind of [Event Sourcing](https://martinfowler.com/eaaDev/EventSourcing.html), then you need to make sure that state change events for one and the same entity get delivered to the subscriber in the order they were created. Parallel delivery of those messages becomes a real issue. Think about `FooUpdated` getting delivered earlier than `FooCreated` with `FooUpdated` holding only the changed attributes. The message consumer will not know what to do with `FooUpdated` in that case and instead of relying on the event stream, the consumer would have to perform an active GET of the data from the origin, which is a significant source of complexity and potential errors.

```gherkin
Scenario: event sourcing using partitioning extension

Given that the partitioning extension was implemented in CloudEvent's SDKs
And the message destination is deliberately offline 
When sending multiple events with the same partitionkey
And after bringing up the message destination
Then the messages that had the same partitionkey are received sequentially by the message destination, retaining the order of message insertion
```

**Comment by slinkydeveloper** [comment]
That's already implemented in sdk-go v2 for kafka. So when you write a message with kafka it will respect the `partitionKey`: https://github.com/cloudevents/sdk-go/blob/master/protocol/kafka_sarama/v2/write_producer_message.go#L24
What is missing is the "materizalized struct", but i don't think there is much value here because it's a 1 key/string value. I close it for now and reopen if you think it's valuable to implement the "materialized struct"
