### ISSUE TITLE
 Add text/plain as a supported content-type in sdk-go

### ISSUE THREAD

**Issue by capri-xiyue** [cloudevents/sdk-go#232]
Currently, text/plain is not a supported content-type in sdk-go.
However, I don't see anything in the http transport binding saying that binary mode events can't be text/plain content-type. Can this be added to sdk-go?

**Comment by alanconway** [comment]
I would go further and say that the SDK should not impose limits on the content-types it allows in events.

Types that are supported by the SDK (like JSON) can get extra treatment - for example Event.SetData() will automatically json.Marshal structs and other data types into JSON if the DataContentType is "application/json". 

However if the DataContentType is unknown,  Event should still be able to simply transport a byte blob with that media-type, without attempting to marshal/unmarshal the data.  

In Go I think either []byte or string are reasonable values for an unknown media type, the SDK should default to []byte (since string sort-of implies unicode) but allow string (since a string is really just a sequence of bytes). No other type would be legal for SetData if the media type is unknown.
