### ISSUE TITLE
Migrate to OpenTelemetry

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/sdk-go#554]
We should look at what it will take to migrate to OpenTelemetry.

One option could be to break out all telemetry integrations and produce two modules, one for what we have with OpenSenses and one with the new OpenTelemetry (it is not 1.0 yet).

Ref:

https://github.com/open-telemetry/opentelemetry-go/

https://opentelemetry.io/

**Comment by joaopgrassi** [comment]
Hi @n3wscott, we briefly discussed on Slack the other day about adding an implementation of the `ObservabilityService` for OpenTelemetry. I have some code working and I was thinking carving it out and sending it upstream. 

Since this issue is older than the PR where the abstraction was introduced (https://github.com/cloudevents/sdk-go/pull/634), I think this is what you meant by "two modules"? 

I was also wondering what about the SDKs for other languages. Do you happen to know if they also intend to have something similar? I couldn't find anything on the spec, apart from the [Distributed tracing extension](https://github.com/cloudevents/spec/blob/v1.0.1/extensions/distributed-tracing.md) which itself doesn't tell much. 

Bringing it up because the Observability service we have today for OpenCensus is rather simple, and some things like the span name and attributes are "hardcoded" and not possible to change/extend. I'm not sure how different are the other SDKs, but if they also want to have something similar as we have in Go, then maybe it's worth putting on the spec?

**Comment by n3wscott** [comment]
I would be so very happy if you wanted to land a module in the https://github.com/cloudevents/sdk-go/tree/main/observability directory for `OpenTelemetry`.

**Comment by joaopgrassi** [comment]
I'm on it 😁. Will send a PR soonish.

**Comment by joaopgrassi** [comment]
@n3wscott PR is there. Hopefully it's not too big to review.
