### ISSUE TITLE
sdk-go for amp protocol is not able to settle 1 out of 10 messages in my POC consitently 

### ISSUE THREAD

**Issue by aneeshkp** [cloudevents/sdk-go#656]
When I used the example to send 10 messages , the client is able to receive only 9 out of 10 messages.
The sender  hangs waiting for  acknowledge for ever. In my opnion it should at least fail or time out, so the sender can resend the message.
 The POC I created  to test this scenario  can be found here, You can recreate this problem either by running in the cluster or stand alone
https://github.com/aneeshkp/cloudevents-amqp
I see following in the QDR logs
```
 ROUTER_CORE (info) [C29][L63] Stuck delivery: At least one delivery on this link has been undelivered/unsettled for more than 10 seconds
 ```
 Sending 10 messages , you can see following message in the log ( its same behaviour if I send 100 messages too, 1 will be not settled)
 ```
 2021/01/19 14:50:26 All 10 message was sent
2021/01/19 14:50:26 Total 1 messages were unsettled
2021/01/19 14:50:26 Unsettled messages
2021/01/19 14:50:26 --------------------
2021/01/19 14:50:26 Message id `2` was not settled and waitng
2021/01/19 14:50:26 --------------------
2021/01/19 14:50:26 Out of 10 messages ,Only 9 was settled

````
with 100 messages 
```
2021/01/19 15:15:59 100 MESSAGE SUCCESSFULLY DELIVERED <nil>
2021/01/19 15:15:59 --------- Summary ----------
2021/01/19 15:15:59 All 100 message was sent
2021/01/19 15:15:59 Total 1 messages were unsettled
2021/01/19 15:15:59 Unsettled messages
2021/01/19 15:15:59 --------------------
2021/01/19 15:15:59 Message id `2` was not settled and waiting
2021/01/19 15:15:59 --------------------
2021/01/19 15:15:59 Out of 100 messages ,Only 99 was settled
```

**Comment by aneeshkp** [comment]
I just found out, if  I blast the qdr with +1 messages with zero sleep time then almost half of them are not settled.
The new code in the above link is able to test this scenario.

**Comment by slinkydeveloper** [comment]
Hi @aneeshkp I tried to investigate a bit and it sounds like a problem of the amqp library, maybe some wrong configuration? The sdk-go code correctly sends the ack back for every message (i checked with your repro), but after the 5th message the receiver remains stuck, because nothing is received from the amqp library receiver.

**Comment by aneeshkp** [comment]
Hi @slinkydeveloper 
I tried to use just amqp library, and it worked. But when I removed `msg. Accept()`, It showed the same behavior. 

It looks like cloudevents sdk  is missing msg.Accept at the receiver side?
```
// Receive next message
			msg, err := receiver.Receive(ctx)
			if err != nil {
				log.Fatal("Reading message from AMQP:", err)
			}

			// Accept message
			msg.Accept()   #<--- looks like this is important
			```

**Comment by n3wscott** [comment]
interesting. Seems like it could be easy to fix. 

which AMQP broker are you using?

**Comment by deissnerk** [comment]
Isn't msg.Accept() called as part of `Finish()`?

**Comment by aneeshkp** [comment]
@n3wscott I am using qpid dispatch router (Broker less)  
https://qpid.apache.org/components/dispatch-router/index.html

**Comment by deissnerk** [comment]
I don't have any experience with the Client abstraction in the SDK. Who is responsible for calling `Finish()` on a message, when using the Client?

**Comment by n3wscott** [comment]
The client calls finish when the invoked function has finished.

**Comment by slinkydeveloper** [comment]
Yep and I checked, it's properly invoked for every of the first 5 messages received

**Comment by atyronesmith** [comment]
The issues seems to be that when a client is created, the link source address of the receiver and the link target address of the transmitter are set to the same value.  This means that transmitted msgs can loop back to the sender.  The address uses balanced deliver so that the first msg goes to the proper destination, but the second msg loops back to sender.  

If line: https://github.com/cloudevents/sdk-go/blob/93f9fa1cd3103d71d1b609a75ec3160ed601b436/protocol/amqp/v2/protocol.go#L57

is modified such that "amqp.LinkSourceAddress(t.Node+"snd"), everything works ok.

The issue is that both a sender and a receiver are created by default without the ability to set a unique source and target address.  Additionally, it is common for an AMPQ connection to be be unidirectional with only either a sender or a receiver client.  A sender is not required to have a receiver and vice-versa.

**Comment by slinkydeveloper** [comment]
@atyronesmith can you provide a fix for that?

**Comment by atyronesmith** [comment]
@slinkydeveloper I will work with @aneeshkp for a fix.  The problem is that NewProtocol only takes a single queue arg,

func NewProtocol(server, queue string, connOption []amqp.ConnOption, sessionOption []amqp.SessionOption, opts ...Option) (*Protocol, error)

NewProtocol creates both a sender and a receiver with the same name.  NewProtocol needs to specify two different names as the transmit queue and receive queues are unrelated.

**Comment by slinkydeveloper** [comment]
Ok so it should get two `queue`, like kafka protocol does right?

**Comment by atyronesmith** [comment]
The Kafka model can be different from AMQP.  For one, AMQP does not require a broker and in cases where predictable, low-latency deliver of messages is required, not broker is used.  Messages travel from the sender to a receiver where, unless multicast has been enable, the msg only goes to a single receiver if multiple receivers are attached and subsequent deliveries are round-robined to the registered receivers.  This is equivalent to Kafka when all the receivers are in the same consumer group.  

For AMQP, a client does not need to have both a target queue and a source queue. Often, an AMQP client is send only.  The underlying protocol doesn't need a separately created receiver queue to operate.  

The NewProtocol signature is part of the design.  Can a new signature be added that has separate names for a send queue and a receive queue.  Or better yet, can an an interface be added that allows the separate creation of a send client and a receive client?

**Comment by slinkydeveloper** [comment]
> Or better yet, can an an interface be added that allows the separate creation of a send client and a receive client?

You can already do that: just create one client with the sender created using this function https://github.com/cloudevents/sdk-go/blob/master/protocol/amqp/v2/sender.go#L36 and one receiver client with the receiver created with this function https://github.com/cloudevents/sdk-go/blob/master/protocol/amqp/v2/receiver.go#L29

> For AMQP, a client does not need to have both a target queue and a source queue. Often, an AMQP client is send only. The underlying protocol doesn't need a separately created receiver queue to operate.

Maybe that's the real issue here: `NewProtocol` doesn't make sense at all to AMQP users and should be removed... Do I understand it correctly?

**Comment by atyronesmith** [comment]
Ok... Cool.  I had missed the individual calls.  I don't think NewProtocol makes sense for AMQP.  I would think it would be better to deprecate its use for AMQP rather than trying to fix it?

**Comment by slinkydeveloper** [comment]
Yeah let's deprecate `NewProtocol` just making it always return an error, so it won't break any code at compile time, but it will always fail preventing people from using it

**Comment by aneeshkp** [comment]
@slinkydeveloper Newprotocol is implemented to bind various types of protocols right?  I think we should just send extra parameters to create either sender or receiver.
I did a quick hack to make it work by passing sender queue and receiver queue and then construct either sender or receiver or both.

**Comment by deissnerk** [comment]
Just a minor remark:
The term `queue` is not really compliant with AMQP terminology. AMQP only knows links with `source` and `target` and does not imply the presence of a queue.
